d3.select('#block')
  .transition('dimensions')
    .duration(600)
    .ease(d3.easeBounceOut)
    .style('width', '400px')
  .transition()
    .duration(600)
    .ease(d3.easeBounceOut)
    .style('height', '600px')

d3.select('#block')
  .transition('color')
    .duration(2000)
    .ease(d3.easeQuadOut)
    .style('background-color', 'purple')
